/* Generated by Yosys 0.33+6 (git sha1 41b34a193, clang 11.0.1-2 -fPIC -Os) */

module Eta_Adder16(a, b_in, sign, sout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  input [15:0] a;
  wire [15:0] a;
  wire [15:0] b;
  input [15:0] b_in;
  wire [15:0] b_in;
  wire ca0;
  wire ca1;
  wire ca2;
  wire ca24;
  wire ca25;
  wire ca26;
  wire ca27;
  wire ca28;
  wire ca29;
  wire ca3;
  wire ca30;
  wire ca31;
  wire ca4;
  wire ca5;
  wire ca6;
  wire [15:0] s;
  input sign;
  wire sign;
  output [15:0] sout;
  wire [15:0] sout;
  assign _43_ = b_in[4] ^ sign;
  assign _44_ = b_in[5] ^ sign;
  assign _45_ = b_in[6] ^ sign;
  assign _46_ = b_in[7] ^ sign;
  assign _47_ = b_in[8] ^ sign;
  assign _00_ = b_in[0] ^ sign;
  assign _01_ = b_in[9] ^ sign;
  assign _02_ = b_in[10] ^ sign;
  assign _03_ = b_in[11] ^ sign;
  assign _04_ = b_in[12] ^ sign;
  assign _05_ = b_in[13] ^ sign;
  assign _06_ = b_in[14] ^ sign;
  assign _07_ = b_in[15] ^ sign;
  assign _11_ = b_in[1] ^ sign;
  assign _22_ = b_in[2] ^ sign;
  assign _33_ = b_in[3] ^ sign;
  Full_Adder a0 (
    .a(a[8]),
    .b(b[8]),
    .c_in(ca31),
    .c_out(_27_),
    .s(_26_)
  );
  Full_Adder a1 (
    .a(a[9]),
    .b(b[9]),
    .c_in(ca0),
    .c_out(_29_),
    .s(_28_)
  );
  Full_Adder a2 (
    .a(a[10]),
    .b(b[10]),
    .c_in(ca1),
    .c_out(_31_),
    .s(_30_)
  );
  Full_Adder a24 (
    .a(a[0]),
    .b(b[0]),
    .c_in(sign),
    .c_out(_09_),
    .s(_08_)
  );
  Full_Adder a25 (
    .a(a[1]),
    .b(b[1]),
    .c_in(ca24),
    .c_out(_12_),
    .s(_10_)
  );
  Full_Adder a26 (
    .a(a[2]),
    .b(b[2]),
    .c_in(ca25),
    .c_out(_14_),
    .s(_13_)
  );
  Full_Adder a27 (
    .a(a[3]),
    .b(b[3]),
    .c_in(ca26),
    .c_out(_16_),
    .s(_15_)
  );
  Full_Adder a28 (
    .a(a[4]),
    .b(b[4]),
    .c_in(ca27),
    .c_out(_18_),
    .s(_17_)
  );
  Full_Adder a29 (
    .a(a[5]),
    .b(b[5]),
    .c_in(ca28),
    .c_out(_20_),
    .s(_19_)
  );
  Full_Adder a3 (
    .a(a[11]),
    .b(b[11]),
    .c_in(ca2),
    .c_out(_34_),
    .s(_32_)
  );
  Full_Adder a30 (
    .a(a[6]),
    .b(b[6]),
    .c_in(ca29),
    .c_out(_23_),
    .s(_21_)
  );
  Full_Adder a31 (
    .a(a[7]),
    .b(b[7]),
    .c_in(ca30),
    .c_out(_25_),
    .s(_24_)
  );
  Full_Adder a4 (
    .a(a[12]),
    .b(b[12]),
    .c_in(ca3),
    .c_out(_36_),
    .s(_35_)
  );
  Full_Adder a5 (
    .a(a[13]),
    .b(b[13]),
    .c_in(ca4),
    .c_out(_38_),
    .s(_37_)
  );
  Full_Adder a6 (
    .a(a[14]),
    .b(b[14]),
    .c_in(ca5),
    .c_out(_40_),
    .s(_39_)
  );
  Full_Adder a7 (
    .a(a[15]),
    .b(b[15]),
    .c_in(ca6),
    .c_out(_42_),
    .s(_41_)
  );
  assign ca0 = _27_;
  assign ca1 = _29_;
  assign ca2 = _31_;
  assign ca3 = _34_;
  assign ca4 = _36_;
  assign ca5 = _38_;
  assign ca6 = _40_;
  assign ca24 = _09_;
  assign ca25 = _12_;
  assign ca26 = _14_;
  assign ca27 = _16_;
  assign ca28 = _18_;
  assign ca29 = _20_;
  assign ca30 = _23_;
  assign ca31 = _25_;
  assign b = { _07_, _06_, _05_, _04_, _03_, _02_, _01_, _47_, _46_, _45_, _44_, _43_, _33_, _22_, _11_, _00_ };
  assign s = { _41_, _39_, _37_, _35_, _32_, _30_, _28_, _26_, _24_, _21_, _19_, _17_, _15_, _13_, _10_, _08_ };
  assign sout = s;
endmodule
