/* Generated by Yosys 0.33+6 (git sha1 41b34a193, clang 11.0.1-2 -fPIC -Os) */

module Full_Adder_Ctrl(a, b, s);
  wire _0_;
  input a;
  wire a;
  input b;
  wire b;
  output s;
  wire s;
  assign _0_ = a | b;
  assign s = _0_;
endmodule
