/* Generated by Yosys 0.33+6 (git sha1 41b34a193, clang 11.0.1-2 -fPIC -Os) */

module Full_Adder(a, b, c_in, s, c_out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  input a;
  wire a;
  input b;
  wire b;
  input c_in;
  wire c_in;
  output c_out;
  wire c_out;
  output s;
  wire s;
  assign _0_ = a ^ b;
  assign _1_ = _0_ ^ c_in;
  assign _2_ = a & b;
  assign _3_ = a & c_in;
  assign _4_ = _2_ | _3_;
  assign _5_ = b & c_in;
  assign _6_ = _4_ | _5_;
  assign s = _1_;
  assign c_out = _6_;
endmodule
