/* Generated by Yosys 0.33+6 (git sha1 41b34a193, clang 11.0.1-2 -fPIC -Os) */

module shift (inshift, counter, oshift);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [15:0] _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input [3:0] counter;
  wire [3:0] counter;
  input [15:0] inshift;
  wire [15:0] inshift;
  wire [15:0] inshift_s;
  output [15:0] oshift;
  wire [15:0] oshift;
  wire [15:0] oshift_s;
  assign _10_ = counter == 4'h2;
  assign _11_ = counter == 4'h3;
  assign _12_ = counter == 4'h4;
  assign _13_ = counter == 4'h5;
  assign _14_ = counter == 4'h6;
  assign _15_ = counter == 4'h7;
  assign _00_ = counter == 4'h0;
  assign _16_ = counter == 4'h8;
  assign _01_ = counter == 4'h9;
  assign _02_ = counter == 4'ha;
  assign _03_ = counter == 4'hb;
  assign _04_ = counter == 4'hc;
  assign _05_ = counter == 4'hd;
  assign _06_ = counter == 4'he;
  assign _07_ = counter == 4'hf;
  function [15:0] \82 ;
    input [15:0] a;
    input [255:0] b;
    input [15:0] s;
    (* parallel_case *)
    casez (s)
    //???????????????
      16'b1:
        \82  = b[15:0];
      16'b1?:
        \82  = b[31:16];
      16'b100:
        \82  = b[47:32];
      16'b0000000000001000:
        \82  = b[63:48];
      16'b0000000000010000:
        \82  = b[79:64];
      16'b0000000000100000:
        \82  = b[95:80];
      16'b0000000001000000:
        \82  = b[111:96];
      16'b0000000010000000:
        \82  = b[127:112];
      16'b0000000100000000:
        \82  = b[143:128];
      16'b0000001000000000:
        \82  = b[159:144];
      16'b0000010000000000:
        \82  = b[175:160];
      16'b0000100000000000:
        \82  = b[191:176];
      16'b0001000000000000:
        \82  = b[207:192];
      16'b0010000000000000:
        \82  = b[223:208];
      16'b0100000000000000:
        \82  = b[239:224];
      16'b1000000000000000:
        \82  = b[255:240];
      default:
        \82  = a;
    endcase
  endfunction
  assign _08_ = \82 (16'h1111, { 15'h0000, inshift_s[15], 14'h0000, inshift_s[15:14], 13'h0000, inshift_s[15:13], 12'h000, inshift_s[15:12], 11'h000, inshift_s[15:11], 10'h000, inshift_s[15:10], 9'h000, inshift_s[15:9], 8'h00, inshift_s[15:8], 7'h00, inshift_s[15:7], 6'h00, inshift_s[15:6], 5'h00, inshift_s[15:5], 4'h0, inshift_s[15:4], 3'h0, inshift_s[15:3], 2'h0, inshift_s[15:2], 1'h0, inshift_s[15:1], inshift_s }, { _07_, _06_, _05_, _04_, _03_, _02_, _01_, _16_, _15_, _14_, _13_, _12_, _11_, _10_, _09_, _00_ });
  assign _09_ = counter == 4'h1;
  assign inshift_s = inshift;
  assign oshift_s = _08_;
  assign oshift = oshift_s;
endmodule
